# https://megalinter.io/configuration/
---
VALIDATE_ALL_CODEBASE: true

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - BASH_SHFMT
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_KICS

SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
